Catkin-ProjectName: genpy
Version: 0.3.0
Description: Willow Garage low level build system macros and infrastructure
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Depends: catkin, genmsg

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: python_distutils
Catkin-ROS-Message-Generator: py

Release-Pull: git://github.com/wg-debs/genpy.git
Release-Push: git@github.com:wg-debs/genpy.git
