Catkin-ProjectName: genpy
Version: 0.3.2
Description: Python code generators for ROS messages
Author: Ken Conley <kwc@willowgarage.com>, Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard
Maintainer: Ken Conley <kwc@willowgarage.com>
Homepage: http://www.ros.org/wiki/genpy

Depends: catkin, genmsg

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: python_distutils
Catkin-ROS-Message-Generator: py
